app: koa-test
stage: dev 
name: scfdemo
component: scf

inputs:
  name: ${name}-${stage}-${app}
  namespace: default
  runtime: Nodejs16.13
  type: web
  src:
    src: ../../src
  cls:
    logsetId: ${output:${stage}:${app}:clsdemo.logsetId}
    topicId: ${output:${stage}:${app}:clsdemo.topicId}
  layers:
    - name: ${output:${stage}:${app}:layerdemo.name}
      version: ${output:${stage}:${app}:layerdemo.version}
  events:
    - apigw:
        parameters:
          environment: release
          endpoints:
            - path: /
              serviceId: ${output:${stage}:${app}:apigwdemo.serviceId}
              method: GET
              function:
                isIntegratedResponse: true
                functionQualifier: $DEFAULT
