app: <%- appName %>
stage: dev 
name: scf-ins
component: scf

inputs:
  name: ${name}-${stage}-${app}
  namespace: default
  runtime: Nodejs16.13
  type: web
  src:
    src: ../../src
  cls:
    logsetId: ${output:${stage}:${app}:cls-ins.logsetId}
    topicId: ${output:${stage}:${app}:cls-ins.topicId}
  layers:
    - name: ${output:${stage}:${app}:layer-ins.name}
      version: ${output:${stage}:${app}:layer-ins.version}
  events:
    - apigw:
        parameters:
          environment: release
          endpoints:
            - path: /
              serviceId: ${output:${stage}:${app}:apigateway-ins.serviceId}
              method: GET
              function:
                isIntegratedResponse: true
                functionQualifier: $DEFAULT
